### ISSUE TITLE
MoE performs worse than equivalent dense model?

### ISSUE THREAD

**Issue by Muennighoff** [mlfoundations/open_lm#253]
Afaict for the numbers reported here https://github.com/mlfoundations/open_lm/pull/115#issuecomment-1858719588 the "1 expert" model is still an MoE, correct?

I also get the result that the 8-expert MoE is better than the 1-expert one, however, both are worse than a dense model. In the below graph `OpenLM-41M` is a 41M dense model and the above two are 8-expert & 1-expert models with 41M active parameters.

<img width="829" alt="Screenshot 2024-04-17 at 2 43 18 PM" src="https://github.com/mlfoundations/open_lm/assets/62820084/a42a4c15-39d6-465a-9de7-b1a6aaa37321">

I would expect the 1-expert to roughly match the dense one & the 8-expert to be better than both but maybe I am missing something? @kernelmachine @sagadre

(My setup follows the main README & https://github.com/mlfoundations/open_lm/blob/main/MOE.md)

**Comment by achalddave** [comment]
Great catch, thanks @Muennighoff! I think this is because the MoE defaults from megablocks differ from our default dense model, in at least two ways: their ffn uses Gelu without gating (`w2 @ gelu(w1 @ x)`) while ours uses swiglu (`w3 @ (silu(w2 @ x) @ (w1 @ x))`), and we use a different parameter init function. 

I'm not sure what the easiest way to reconcile these is. Probably we want a custom version of the MLP class here https://github.com/databricks/megablocks/blob/2724ff6775ee7e2a41001a7979c0ec84c417cd84/megablocks/layers/mlp.py#L81-L137 that implements swiglu and our init function.

**Comment by Muennighoff** [comment]
I trained an OpenLM model with the Gelu & tanh approximate used in megablocks and regular normal init by adding the below two in `model.py`:

```python
        elif args.ffn_type == "gelutanh":
            self.hidden_dim = args.dim * 4
            self._ff_w1 = nn.Linear(args.dim, self.hidden_dim, bias=False)
            self._ff_w2 = nn.Linear(self.hidden_dim, args.dim, bias=False)
            self.feed_forward = nn.Sequential(self._ff_w1, nn.GELU(approximate="tanh"), self._ff_w2)    
```

&

```python
        elif self._ffn_type == "gelutanh":
            torch.nn.init.normal_(self._ff_w1.weight, mean=0.0, std=0.02)
            torch.nn.init.normal_(self._ff_w2.weight, mean=0.0, std=0.02)
```

It does indeed perform slightly worse than the regular 41M but still far better than the MoE variants. (For the 8 expert one params increased from 69M ot 97M as I increased MoE frequency to every layer instead of every 2nd). Do you have any more ideas where this could come from?

<img width="814" alt="Screenshot 2024-04-18 at 11 49 13 AM" src="https://github.com/mlfoundations/open_lm/assets/62820084/0d01aab9-b753-4bcf-b9e8-dc647f1991bb">
